import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "@/components/ui/sonner";
import "@rainbow-me/rainbowkit/styles.css";
import Web3Provider from "@/lib/Web3Provider";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const extensionHydrationCleanupScript = `
(function () {
  var attributeName = "bis_skin_checked";

  function clean(root) {
    if (!root || root.nodeType !== 1) {
      return;
    }

    if (root.hasAttribute && root.hasAttribute(attributeName)) {
      root.removeAttribute(attributeName);
    }

    if (!root.querySelectorAll) {
      return;
    }

    var nodes = root.querySelectorAll("[" + attributeName + "]");
    for (var i = 0; i < nodes.length; i += 1) {
      nodes[i].removeAttribute(attributeName);
    }
  }

  clean(document.documentElement);

  if (!window.MutationObserver) {
    return;
  }

  var observer = new MutationObserver(function (mutations) {
    for (var i = 0; i < mutations.length; i += 1) {
      var mutation = mutations[i];

      if (mutation.type === "attributes") {
        clean(mutation.target);
      }

      for (var j = 0; j < mutation.addedNodes.length; j += 1) {
        clean(mutation.addedNodes[j]);
      }
    }
  });

  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: [attributeName],
    childList: true,
    subtree: true
  });

  window.setTimeout(function () {
    observer.disconnect();
  }, 5000);
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Web3Provider>
          <TooltipProvider>
            {children}
            <Toaster closeButton position="top-right" richColors />
          </TooltipProvider>
        </Web3Provider>
        <Script
          id="extension-hydration-cleanup"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: extensionHydrationCleanupScript }}
        />
      </body>
    </html>
  );
}
